apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: major-louse-go 
  janus-idp.io/tekton: major-louse-go
  backstage.io/kubernetes-id: major-louse-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: major-louse-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  